/*
 * generated by Xtext
 */
package org.xtext.example.firstdsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class LangOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
