/*
 * generated by Xtext
 */
package org.xtext.example.seconddsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LangRuntimeModule extends org.xtext.example.seconddsl.AbstractLangRuntimeModule {

}
