/*
 * generated by Xtext
 */
package org.xtext.example.seconddsl.ui.contentassist

import org.xtext.example.seconddsl.ui.contentassist.AbstractLangProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LangProposalProvider extends AbstractLangProposalProvider {
}
