/*
 * generated by Xtext
 */
package org.xtext.example.firstdsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LangUiModule extends AbstractLangUiModule {
}
