/*
 * generated by Xtext
 */
package org.xtext.example.firstdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LangUiModule extends org.xtext.example.firstdsl.ui.AbstractLangUiModule {
	public LangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
