/*
 * generated by Xtext
 */
package org.xtext.example.firstdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LangRuntimeModule extends AbstractLangRuntimeModule {
}
